package(default_visibility = ["//visibility:public"])

py_library(
    name = "merge_sort",
    srcs = [
        "merge_sort.py",
    ],
)

py_library(
    name = "insertion_sort",
    srcs = [
        "insertion_sort.py",
    ],
)
