package(default_visibility = ["//visibility:public"])

py_library(
    name = "bucket_sort",
    srcs = [
        "bucket_sort.py",
    ],
    deps = [
        "//chapter2:insertion_sort",
    ],
)

py_library(
    name = "counting_sort",
    srcs = [
        "counting_sort.py",
    ],
)

py_library(
    name = "radix_sort",
    srcs = [
        "radix_sort.py"
    ],
)